api/urls.py
from django.conf.urls import url
from rest_framework import routers

from api.views import (LoginUserViewSet, SettlementAPIView, SwapView,
                       GetLateLeftAPIView, EnterExitAPIView,
                       BedDetailView, TentDetailView, StatesView,
                       LoginVIPUserViewSet, CitiesListView, GetShiftsLate,
                       RemainedBedsView, TentForceSettlementView)

urlpatterns = [
    url(r'^settle_bed/$', SettlementAPIView.as_view(), name='settlement_bed'),
    url(r'^gate_pass/$', EnterExitAPIView.as_view(), name='gate_pass'),
    url(r'^get_late_entrance/(?P<margin>.*)/$', GetLateLeftAPIView.as_view(), name='assign_bed_vip'),
    url(r'^get_bed/(?P<title>.*)/$', BedDetailView.as_view(), name='bed_detail'),
    url(r'^get_tent/$', TentDetailView.as_view(), name='tent_detail'),
    url(r'^get_states/$', StatesView.as_view(), name='state_views'),
    url(r'^get_cities/(?P<state_id>.*)/$', CitiesListView.as_view(), name='city_views'),
    url(r'^swap_bed/$', SwapView.as_view(), name='swap_bed'),
    url(r'^shifts_report/$', GetShiftsLate.as_view(), name='shifts_report'),

    url(r'^remained/$', RemainedBedsView.as_view(), name='remain_beds_view'),
    url(r'^tents/(?P<tent_id>\d+)/$', TentForceSettlementView.as_view(), name='tent_force_settlement_view'),
]

router = routers.SimpleRouter()
router.register(r'guests', LoginUserViewSet)
router.register(r'vip', LoginVIPUserViewSet)
router.register(r'staff', LoginVIPUserViewSet)
urlpatterns += router.urls

tent/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework.documentation import include_docs_urls

from rest_framework_swagger.views import get_swagger_view

from guest import views

schema_view = get_swagger_view(title='Pastebin API')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('users.urls')),
    url(r'^api/', include('api.urls')),
    # url(r'^docs/', schema_view),
    url('docs/', include_docs_urls(title='Mokeb API Documentation')),
    url(r'^panel/', include('panel.urls')),
    url(r'^clinic/', include('hospital.urls')),
    url(r'^$', views.GuestRegister.as_view(), name='home'),
    url(r'^guest/(?P<passport_code>.+)/$', views.GuestDetail.as_view()),
    url(r'^rosetta/', include('rosetta.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

guest/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import os
import barcode

from django.conf import settings
from django.core import validators
from django.db import models
from django.utils.translation import ugettext_lazy as _


from location.models import State, City
from shift.models import Shift
from .manager import BedAvailableManager, BedUnAvailableManager


class Guest(models.Model):
    NORMAL = 1
    STAFF = 2
    VIP = 3

    first_name = models.CharField(verbose_name=_('First name'), max_length=50)
    last_name = models.CharField(verbose_name=_('Last name'), max_length=50)
    passport_code = models.CharField(verbose_name=_('Passport code'), unique=True, max_length=10, db_index=True)
    national_code = models.CharField(verbose_name=_('National code'), blank=True, null=True, max_length=10, db_index=True)
    profile_picture = models.ImageField(verbose_name=_('Profile pic'), upload_to='profile_pic', blank=True, null=True)
    passport_picture = models.ImageField(verbose_name=_('Passport pic'), upload_to='passport_pic', blank=True, null=True)
    mobile_number = models.BigIntegerField(
        verbose_name=_('Mobile number'), unique=True,
        validators=[validators.RegexValidator(r'^9[0-3,9]\d{8}$', _('Enter a valid mobile number.'), 'invalid')],
        error_messages={'unique': _("A user with this mobile number already exists.")}
    )
    phone_number = models.BigIntegerField(verbose_name=_('Home phone number'), null=True, blank=True,)
    state = models.ForeignKey(State, verbose_name=_('State'), null=True, blank=True)
    city = models.ForeignKey(City, verbose_name=_('City'), null=True, blank=True)
    birthday = models.CharField(verbose_name=_('Birth date'), max_length=64, blank=True, null=True)

    created_at = models.DateTimeField(verbose_name=_('Registered'), auto_now_add=True)
    modified_at = models.DateTimeField(verbose_name=_('Modified'), auto_now=True)
    printed = models.BooleanField(default=False, verbose_name=_("card printed"))
    white_list = models.BooleanField(default=False, verbose_name=_("white list"))
    accepted_terms = models.BooleanField(default=False, verbose_name=_("accepted_terms"))

    @property
    def first_enter_datetime(self):
        datetime = self.logs.filter(log_type=EntryLog.ENTER).order_by('time').first()
        if datetime:
            return datetime.time

    @property
    def barcode(self):
        path = 'media/barcode/'
        if not os.path.exists(path):
            os.makedirs(path)
        path += self.passport_code + '.svg'
        if not os.path.exists(path):
            ean = barcode.get('code39', self.passport_code)
            ean.save(path[:-4])
        return path

    @property
    def has_bed(self):
        return hasattr(self, 'guest_bed')

    @property
    def bed(self):
        if self.has_bed:
            return self.guest_bed.bed

    @property
    def type(self):
        if self.has_bed:
            return self.bed.bed_type

    @property
    def shift(self):
        if self.first_enter_datetime:
            shift = Shift.objects.filter(
                start_date__lte=self.first_enter_datetime, end_date__gte=self.first_enter_datetime
            ).first()
            return shift
        return None

    @property
    def fullname(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def get_absolute_url(self):
        return "guest/%s/" % self.passport_code

    def __str__(self):
        return "%s %s %s" % (self.first_name, self.last_name, self.passport_code)

    class Meta:
        verbose_name = _('guest')
        verbose_name_plural = _('guests')
        db_table = 'guest'


class Tent(models.Model):
    GUEST = 1
    STAFF = 2
    VIP = 3

    TYPE_CHOICE = (
        (VIP, _('Vip')),
        (STAFF, _('Staff')),
        (GUEST, _('Guest')),
    )

    tent_type = models.IntegerField(choices=TYPE_CHOICE, default=GUEST, verbose_name=_('type of tent'),)
    priority = models.PositiveIntegerField(verbose_name=_('priority'))
    capacity = models.PositiveIntegerField(verbose_name=_('capacity'))

    def __str__(self):
        return '%s %s' % (self.get_tent_type_display(), self.priority)

    @property
    def title(self):
        title = {1: 'G', 2: 'S', 3: 'V',}
        return '%s%s' % (title[self.tent_type], self.priority)

    class Meta:
        ordering = ['priority']
        unique_together = ('tent_type', 'priority')
        verbose_name = _('tent')
        verbose_name_plural = _('tents')
        db_table = 'tent'


class Bed(models.Model):
    REAL_BED = 1
    IMPLICIT_BED = 2

    AVAILABLE = 1
    UNAVAILABLE = 2
    SUSPENDED = 3

    BED_CHOICE = (
        (REAL_BED, _('Real Bed')),
        (IMPLICIT_BED, _('Implicit Bed')),
    )

    STATUS_CHOICE = (
        (AVAILABLE, _('Available')),
        (UNAVAILABLE, _('Unavailable')),
        (SUSPENDED, _('Suspended')),
    )

    bed_type = models.IntegerField(choices=BED_CHOICE, default=REAL_BED)
    tent = models.ForeignKey(Tent, on_delete=models.CASCADE, related_name='beds')
    status = models.IntegerField(choices=STATUS_CHOICE, default=AVAILABLE)
    title = models.CharField(max_length=16, editable=False, db_index=True)
    type_index = models.IntegerField(editable=False)

    objects = models.Manager()
    available = BedAvailableManager()
    unavailable = BedUnAvailableManager()

    def __str__(self):
        return '%s in tent %s,id %s' % (self.get_bed_type_display(), self.tent.id, self.id)

    @classmethod
    def get_last_available_bed_q(cls, operator, tent_type=1):
        allocation = operator.allocation
        return allocation.get_available_bed(tent_type)

    @property
    def guest(self):
        if hasattr(self, 'guest_bed'):
            return self.guest_bed.guest

    def save(self, *args, **kwargs):
        if not self.id:
            self.title, self.type_index = self.set_static()
        super(Bed, self).save(*args, **kwargs)

    def set_available(self):
        self.status = self.AVAILABLE
        self.save()

    def set_unavailable(self):
        self.status = self.UNAVAILABLE
        self.save()

    def set_static(self):
        count = Bed.objects.filter(tent=self.tent).count() + 1
        title = '%s%s' % (self.tent.title, str(count).zfill(3))
        return title, count

    class Meta:
        verbose_name = _('bed')
        verbose_name_plural = _('beds')
        db_table = 'bed'


class EntryLog(models.Model):
    ENTER = 1
    EXIT = 2
    SETTLEMENT = 3
    FORCE_SETTLEMENT = 4
    SWAP = 5
    ENTER_CHOICES = (
        (ENTER, _('Enter')),
        (EXIT, _('Exit')),
        (SETTLEMENT, _('Settlement')),
        (FORCE_SETTLEMENT, _('Force Settlement')),
        (SWAP, _('Swap')),
    )
    guest = models.ForeignKey(Guest, on_delete=models.CASCADE, related_name='logs', verbose_name=_('guest'))
    time = models.DateTimeField(auto_now_add=True, verbose_name=_('time'), )
    log_type = models.IntegerField(choices=ENTER_CHOICES, verbose_name=_('log type'))
    operator = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='logs', verbose_name=_('operator')
    )
    bed = models.ForeignKey(Bed, on_delete=models.CASCADE, related_name='logs', verbose_name=_('bed'))

    class Meta:
        verbose_name = _('log')
        verbose_name_plural = _('logs')
        db_table = 'entry_log'


class GuestBed(models.Model):
    """Tmp table for storing bed and guest relationship and normalize data reading
    this table will modify after assign_bed, settle_bed, shift_bed, force_settle"""
    tent = models.ForeignKey(Tent, related_name='guests_beds')
    bed = models.OneToOneField(Bed, related_name='guest_bed')
    guest = models.OneToOneField(Guest, related_name='guest_bed')
    log = models.OneToOneField(EntryLog, null=True)

    class Meta:
        db_table = 'guest_bed'
        verbose_name = _("Guests Bed")
        verbose_name_plural = _("Guests Beds")

guest/forms.py
from django.forms import ModelForm, HiddenInput
from guest.models import Guest
from location.models import State, City


class RegisterForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs = {'class': 'form-control'}
        self.fields['last_name'].widget.attrs = {'class': 'form-control'}
        self.fields['passport_code'].widget.attrs = {'class': 'form-control'}
        # self.fields['national_code'].widget.attrs = {'class': 'form-control'}
        self.fields['mobile_number'].widget.attrs = {'class': 'form-control'}
        # self.fields['phone_number'].widget.attrs = {'class': 'form-control'}
        # self.fields['city'].widget.attrs = {'class': 'form-control'}
        # self.fields['state'].widget.attrs = {'class': 'form-control'}

        self.fields['first_name'].label = u'نام'
        self.fields['last_name'].label = u'نام خانوادگی'
        self.fields['passport_code'].label = u'شماره گذرنامه'
        # self.fields['national_code'].label = u'کد ملی'
        self.fields['mobile_number'].label = u'شماره موبایل'
        # self.fields['phone_number'].label = u'شماره تلفن'
        # self.fields['city'].label = u'شهر'
        # self.fields['state'].label = u'استان'

    def save(self, commit=True):
        instance = super(RegisterForm, self).save(False)
        if commit:
            instance.save()
        return instance

    class Meta:
        model = Guest
        fields = ('first_name', 'last_name', 'passport_code', 'mobile_number')

guest/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import Http404
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import get_object_or_404

from .models import Guest
from .forms import RegisterForm


class GuestRegister(CreateView):
    form_class = RegisterForm
    template_name = 'guest/guest_form.html'


class GuestDetail(DetailView):
    model = Guest
    lookup = 'passport_code'
    queryset = Guest.objects.select_related('city', 'state')

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()

        passport_code = self.kwargs.get(self.lookup)
        if passport_code is not None:
            queryset = queryset.filter(passport_code=passport_code)

        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404(_("No %(verbose_name)s found matching the query") %
                          {'verbose_name': queryset.model._meta.verbose_name})
        return obj

guest/templates/guest/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>سامانه ثبت زائر</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">-->
    <link rel="stylesheet" href="{% static 'guest/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'guest/css/bootstrap-rtl.min.css' %}"/>
    <!--<link rel="stylesheet" href="https://cdn.rawgit.com/morteza/bootstrap-rtl/v3.3.4/dist/css/bootstrap-rtl.min.css">-->
</head>
<body>
{% block contents %}
{% endblock %}

{% block static %}
{% endblock %}
</body>
</html>

guest/templates/guest/card.html
{% load convert_data %}
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css"
          href="{% static 'guest/css/print.css' %}">
</head>
<body>
{% if object.profile_picture %}
<div class="img-section">
    <img src="{{object.profile_picture.url}}" class="profile">
</div>
<div class="container">
    <div>
        <p class="name"><span class="title"></span><span class="detail">{{object.first_name}} {{object.last_name}}</span></p>
    </div>
    <div class='third-row'>
        <p class="third-detail">
            <!--<span class="detail"></span>-->
            <span class="title">{{object.passport_code|slice:"1:"}} </span>
            <span class="detail"></span>
            <span class="title">{% convert object.first_enter_datetime %}</span>
        </p>
    </div>
    <div class='forth-row'>
        <p><span class="title"></span> {{object.bed.type_index}}، <span class="title"></span> {{object.bed.tent.title}}</p>
    </div>
</div>
<div>
    <div>
        <img src="/{{object.barcode}}" class="barcode">
    </div>
</div>
{% else %}
<center>
    <p>Not Enough details provided</p>
</center>
{% endif %}
</body>
</html>

guest/templates/guest/guest_detail.html
{% extends 'guest/base.html' %}
{% block contents %}
    <div class="container">
        <div class="row">
            <div class=".col-md-12">
                <h1>اطلاعات ثبت شده در سامانه</h1>
                <p>نام: {{ object.first_name }}</p>
                <p>نام خانوادگی: {{ object.last_name }}</p>
                <p>شماره گذرنامه: {{ object.passport_code }}</p>

                <p>شماره موبایل: {{ object.mobile_number }}</p>
                <p>زمان ثبت اطلاعات: {{ object.created_at }}</p>
            </div>
        </div>
    </div>

{% endblock %}

guest/templates/guest/guest_form.html
{% extends 'guest/base.html' %}
{% load staticfiles %}
{% block contents %}

    <br><br><br><br><br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-xs-12">
                <h4 class="text-warning">وارد کردن تمامی فیلدها الزامی است</h4>
            </div>
            <div class="col-md-6 col-xs-12">
                <div class="form-group" >
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.first_name.errors }}
                            {{ form.first_name.label }}
                            {{ form.first_name }}
                        </div>
                        <div class="form-group">
                            {{ form.last_name.errors }}
                            {{ form.last_name.label }}
                            {{ form.last_name }}
                        </div>
                        <div class="form-group">
                            {{ form.passport_code.errors }}
                            {{ form.passport_code.label }}
                            {{ form.passport_code }}
                        </div>
                        <div class="form-group">
                            {{ form.mobile_number.errors }}
                            {{ form.mobile_number.label }}
                            {{ form.mobile_number }}
                            <p class="text-info">مثال: 09121234567</p>
                        </div>
                        <button class="btn btn-primary" type="submit" id="myBtn">ارسال</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block static %}
                    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
                    <script>
                        $( "#id_state" ).change(
                            function (state_id) {
                            console.log("function init")
                            var l = window.location
                            var baseUrl = l.protocol + "//" + l.host + "/" + l.pathname.split('/')[1];
                            var path = baseUrl + "api/get_cities" + "/" + this.value + "/";
                            $.ajax({url: path, success: function(cities){
                                $("#id_city").html("");
                                    for (i = 0; i < cities.length; i++) {
                                        $("#id_city").append("<option value='" + cities[i].id + "'>" + cities[i].city_name + "</option>");
                                    }
                            }
                        });
                        });
                    </script>
{% endblock %}

guest/templates/guest/guest_unprinted.html
{% extends 'guest/base.html' %}
{% block contents %}
    <div class="container">
        <div class="col-lg-12">
            <div class="row">
                <p class="text-info">
                    کد ملی را برای چاپ دوباره وارد کنید
                </p>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="row">
                <form>
                    <div class="input-group">
                        <input type="text" class="form-control" name="search"
                               id="search">
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="button"
                                onclick="window.open(
                                    document.getElementById('search').value);">چاپ
                        </button>
                        </span>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="row">
                <table class="table">
                    <thead>
                        <tr>
                            <th>نام</th>
                            <th>نام خانوادگی</th>
                            <th>کد ملی</th>
                            <th>چاپ</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for object in object_list %}
                        <tr>
                            <td>{{ object.first_name }}</td>
                            <td>{{ object.last_name }}</td>
                            <td>{{ object.national_code }}</td>
                            <td>
                                <a target="_blank" class="btn btn-info" role="button" href="{% url 'card_detail' national_code=object.national_code %}">چاپ</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

guest/templates/guest/unprinted_guest_detail.html
{% block contents %}
    <h3>hello world</h3>
    {% for object in object_list %}
        <h6>{{ object.national_code }}</h6>
    {% endfor %}
{% endblock %}