api/urls.py
from django.conf.urls import url
from rest_framework import routers

from api.views import (LoginUserViewSet, SettlementAPIView, SwapView,
                       GetLateLeftAPIView, EnterExitAPIView,
                       BedDetailView, TentDetailView, StatesView,
                       LoginVIPUserViewSet, CitiesListView, GetShiftsLate,
                       RemainedBedsView, TentForceSettlementView)

urlpatterns = [
    url(r'^settle_bed/$', SettlementAPIView.as_view(), name='settlement_bed'),
    url(r'^gate_pass/$', EnterExitAPIView.as_view(), name='gate_pass'),
    url(r'^get_late_entrance/(?P<margin>.*)/$', GetLateLeftAPIView.as_view(), name='assign_bed_vip'),
    url(r'^get_bed/(?P<title>.*)/$', BedDetailView.as_view(), name='bed_detail'),
    url(r'^get_tent/$', TentDetailView.as_view(), name='tent_detail'),
    url(r'^get_states/$', StatesView.as_view(), name='state_views'),
    url(r'^get_cities/(?P<state_id>.*)/$', CitiesListView.as_view(), name='city_views'),
    url(r'^swap_bed/$', SwapView.as_view(), name='swap_bed'),
    url(r'^shifts_report/$', GetShiftsLate.as_view(), name='shifts_report'),

    url(r'^remained/$', RemainedBedsView.as_view(), name='remain_beds_view'),
    url(r'^tents/(?P<tent_id>\d+)/$', TentForceSettlementView.as_view(), name='tent_force_settlement_view'),
]

router = routers.SimpleRouter()
router.register(r'guests', LoginUserViewSet)
router.register(r'vip', LoginVIPUserViewSet)
router.register(r'staff', LoginVIPUserViewSet)
urlpatterns += router.urls

hospital/urls.py
from django.conf.urls import url

from hospital.views import ClinicMainView, ExaminationsListView, DrugStoreListView

urlpatterns = [
    url(r'^$', ClinicMainView.as_view(), name='clinic'),
    url(r'^examinations/$', ExaminationsListView.as_view(), name='examinations'),
    url(r'^drugstore/$', DrugStoreListView.as_view(), name='drugstore'),
]

tent/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework.documentation import include_docs_urls

from rest_framework_swagger.views import get_swagger_view

from guest import views

schema_view = get_swagger_view(title='Pastebin API')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('users.urls')),
    url(r'^api/', include('api.urls')),
    # url(r'^docs/', schema_view),
    url('docs/', include_docs_urls(title='Mokeb API Documentation')),
    url(r'^panel/', include('panel.urls')),
    url(r'^clinic/', include('hospital.urls')),
    url(r'^$', views.GuestRegister.as_view(), name='home'),
    url(r'^guest/(?P<passport_code>.+)/$', views.GuestDetail.as_view()),
    url(r'^rosetta/', include('rosetta.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hospital/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Sum
from django.db.models.functions import Coalesce
from django.utils.translation import ugettext_lazy as _

from guest.models import Guest


User = get_user_model()


class Drug(models.Model):
    name = models.CharField(verbose_name=_("name"), max_length=64)
    description = models.TextField(verbose_name=_("description"), blank=True)

    created_time = models.DateTimeField(verbose_name=_("created time"), auto_now_add=True)
    modified_time = models.DateTimeField(verbose_name=_("modified time"), auto_now=True)

    class Meta:
        verbose_name = _("Drug")
        verbose_name_plural = _("Drugs")

    def __str__(self):
        return self.name

    @property
    def quantity(self):
        return self.entities.aggregate(s=Coalesce(Sum('quantity'), 0))['s'] - self.examinations.aggregate(s=Coalesce(Sum('quantity'), 0))['s']


class Pharmacy(models.Model):
    drug = models.ForeignKey(Drug, verbose_name=_("drug"), related_name='entities')
    quantity = models.PositiveSmallIntegerField(verbose_name=_("quantity"))

    created_time = models.DateTimeField(verbose_name=_("created time"), auto_now_add=True)
    modified_time = models.DateTimeField(verbose_name=_("modified time"), auto_now=True)

    class Meta:
        verbose_name = _("Pharmacy")
        verbose_name_plural = _("Pharmacy")

    def __str__(self):
        return "{}: {}".format(self.drug, self.quantity)


class Examination(models.Model):
    guest = models.ForeignKey(Guest, verbose_name=_("guest"), related_name='examinations')
    diagnosis = models.TextField(blank=True, verbose_name=_("diagnosis"))
    drugs = models.ManyToManyField(Drug, through="ExaminationDrug")

    user = models.ForeignKey(User, related_name='examinations', blank=True, null=True, editable=False)
    created_time = models.DateTimeField(verbose_name=_("created time"), auto_now_add=True)
    modified_time = models.DateTimeField(verbose_name=_("modified time"), auto_now=True)

    class Meta:
        verbose_name = _("Examination")
        verbose_name_plural = _("Examinations")


class ExaminationDrug(models.Model):
    examination = models.ForeignKey(Examination, verbose_name=_("examination"))
    drug = models.ForeignKey(Drug, verbose_name=_("drug"), related_name='examinations')
    quantity = models.PositiveSmallIntegerField(verbose_name=_("quantity"))

    created_time = models.DateTimeField(verbose_name=_("created time"), auto_now_add=True)
    modified_time = models.DateTimeField(verbose_name=_("modified time"), auto_now=True)

    class Meta:
        verbose_name = _("ExaminationDrug")
        verbose_name_plural = _("ExaminationDrugs")

hospital/views.py
from django.views.generic import TemplateView, ListView

from hospital.models import Examination, Drug


class ClinicMainView(TemplateView):
    """
    Main view of panel should provide a list of all available urls for
    web operator of system urls may modify manually
    """

    template_name = 'hospital/clinic_panel.html'


class ExaminationsListView(ListView):
    model = Examination
    queryset = Examination.objects.select_related('guest').all().order_by('-created_time')
    template_name = 'hospital/examination_list.html'


class DrugStoreListView(ListView):
    model = Drug
    queryset = Drug.objects.all().order_by('-id')
    template_name = 'hospital/drugstore.html'

hospital/templates/hospital/clinic_panel.html
{% extends 'panel/panel_base.html' %}
{% load staticfiles %}
{% block title %} مرکز درمانی{% endblock %}
{% block content %}
<div class="url row">

	<div class="col-md-4 col-sm-6 col-12 pb-4">
		<a class="btn btn-info btn-block" href="{% url 'drugstore' %}" target=_blank>لیست موجودی داروخانه</a>
	</div>
	<div class="col-md-4 col-sm-6 col-12 pb-4">
		<a class="btn btn-hospital-green btn-block" href="{% url 'examinations' %}" target=_blank>لیست معاینات پزشکی</a>
	</div>
	<div class="col-md-4 col-sm-6 col-12 pb-4">
		<a class="btn btn-purple btn-block" href="/admin/hospital/examination/add/" target=_blank>معاینه جدید</a>
	</div>
</div>
{% endblock %}

hospital/templates/hospital/drugstore.html
{% extends 'panel/panel_base.html' %}
{% load convert_data %}
{% load staticfiles %}
{% block title %}لیست دارو‌های موجود{% endblock %}
{% block content %}
<div class="col-lg-12">
    <div class="row">
        <table class="table table-light text-center table-bordered">
            <thead>
                <tr>
                    <th scope="col">نام دارو</th>
                    <th scope="col">توضیحات</th>
                    <th scope="col">تعداد باقی‌مانده</th>
                </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <td>{{ object.name }}</td>
                    <td>{{ object.description }}</td>
	                <td>{{ object.quantity }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

hospital/templates/hospital/examination_list.html
{% extends 'panel/panel_base.html' %}
{% load convert_data %}
{% load staticfiles %}
{% block title %}لیست همه معاینات{% endblock %}
{% block content %}
<div class="col-lg-12">
    <div class="row">
        <a class="btn btn-purple" href="/admin/hospital/examination/add/">ثبت معاینه جدید</a>
    </div>
</div>
<br>
<div class="col-lg-12">
    <div class="row">
        <table class="table table-light text-center table-bordered">
            <thead>
                <tr>
                    <th scope="col">نام مهمان</th>
                    <th scope="col">تشخیص</th>
                    <th scope="col">دارو‌های تجویز شده</th>
                    <th scope="col">تاریخ مراجعه</th>
                </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <td>{{ object.guest.fullname }}</td>
                    <td>{{ object.diagnosis }}</td>
                    <td>{% for drug in object.examinationdrug_set.all %}{{ drug.drug.name }}({{ drug.quantity}}), {% endfor %}</td>
	                <td>{% convert object.created_time %}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}